import styles from './adminView.module.css'
import {useState} from 'react'
import UserManagementTable from "../../components/user-management-table/UserManagementTable";
import {Alert, Button, Snackbar, Typography} from "@mui/material";
import {SnackbarAlert} from "../../utils/snackbar-alert";
import Header from "../../components/header/Header";
import {Terminal} from '@mui/icons-material';
import {RunCustomSQL} from "../../../wailsjs/go/main/App";

export default function AdminView() {
    const [alert, showAlert] = useState<SnackbarAlert | null>(null)

    const handleRunSQLScript = () => {
        RunCustomSQL()
            .then(() => showAlert({
                severity: 'success',
                msg: 'SQL script executed successfully.'
            })).catch((err) => showAlert({
                severity: 'error',
                msg: err
            }))
    }

    return (
        <div className={styles.adminView}>
            <Header title='Admin Portal' />

            <div className={styles.contentCard}>
                <div className={styles.contentCardHeader}>
                    <h2 className={styles.sectionTitle}>Manage Users</h2>
                </div>
                <div className={styles.contentCardDivider}></div>
                <div className={styles.contentCardContent}>
                    <UserManagementTable onAlert={showAlert} />
                </div>
            </div>

            <div className={styles.contentCard}>
                <div className={styles.contentCardHeader}>
                    <h2 className={styles.sectionTitle}>Run Custom SQL Scripts</h2>
                </div>
                <div className={styles.contentCardDivider}></div>
                <div className={styles.contentCardContent}>
                    <Alert severity='error'>
                        <Typography>
                            Warning: Only run scripts generated by trusted sources.
                        </Typography>
                    </Alert>
                    <Button onClick={handleRunSQLScript}
                            variant='outlined'
                            sx={{mt: 2}}
                            startIcon={<Terminal />}
                    >
                        Select script and run
                    </Button>
                </div>
            </div>

            {alert && (
                <Snackbar
                    open={!!alert}
                    autoHideDuration={6000}
                    onClose={() => showAlert(null)}
                    anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
                >
                    <Alert severity={alert.severity} onClose={() => showAlert(null)}>
                        {alert.msg}
                    </Alert>
                </Snackbar>
            )}
        </div>
    )
}