// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignRecordLocator(arg1) {
  return window['go']['main']['App']['AssignRecordLocator'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetDefaultSearchMode() {
  return window['go']['main']['App']['GetDefaultSearchMode']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function SearchModeBoolean(arg1) {
  return window['go']['main']['App']['SearchModeBoolean'](arg1);
}

export function SearchModeFullText(arg1) {
  return window['go']['main']['App']['SearchModeFullText'](arg1);
}

export function SearchModeFullTextWithQueryExpansion(arg1) {
  return window['go']['main']['App']['SearchModeFullTextWithQueryExpansion'](arg1);
}

export function SearchModeRegular(arg1, arg2) {
  return window['go']['main']['App']['SearchModeRegular'](arg1, arg2);
}

export function SetDefaultSearchMode(arg1) {
  return window['go']['main']['App']['SetDefaultSearchMode'](arg1);
}

export function UpdateAsset(arg1) {
  return window['go']['main']['App']['UpdateAsset'](arg1);
}
