// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAsset(arg1:Record<string, string>):Promise<number>;

export function AssignRecordLocator(arg1:number):Promise<void>;

export function ChangeImage(arg1:number):Promise<boolean>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function DownloadManual(arg1:number,arg2:number):Promise<boolean>;

export function DownloadReceipt(arg1:number):Promise<boolean>;

export function DuplicateAsset(arg1:number):Promise<number>;

export function ExportAssetsCSV(arg1:Array<number>):Promise<void>;

export function ExportAssetsPDF(arg1:Array<number>):Promise<void>;

export function GetAsset(arg1:number):Promise<main.Asset>;

export function GetDefaultSearchMode():Promise<string>;

export function GetGroupAssets(arg1:number):Promise<Array<main.GroupAsset>>;

export function GetGroups():Promise<Array<main.Group>>;

export function GetProductVersion():Promise<string>;

export function GetUsers():Promise<Array<main.User>>;

export function Login(arg1:string,arg2:string):Promise<number>;

export function RemoveImage(arg1:number):Promise<void>;

export function RemoveManual(arg1:number):Promise<void>;

export function RemoveReceipt(arg1:number):Promise<void>;

export function SearchModeBoolean(arg1:string):Promise<Array<main.Asset>>;

export function SearchModeFullText(arg1:string):Promise<Array<main.Asset>>;

export function SearchModeFullTextWithQueryExpansion(arg1:string):Promise<Array<main.Asset>>;

export function SearchModeRegular(arg1:string,arg2:string):Promise<Array<main.Asset>>;

export function SelectFile(arg1:string):Promise<string>;

export function SetDefaultSearchMode(arg1:string):Promise<void>;

export function ToggleMissing(arg1:number,arg2:boolean,arg3:string):Promise<void>;

export function UpdateAsset(arg1:number,arg2:Record<string, string>):Promise<void>;

export function UpdateUserAccessLevel(arg1:main.User):Promise<void>;

export function UploadManual(arg1:number):Promise<boolean>;

export function UploadReceipt(arg1:number):Promise<boolean>;
