// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAsset(arg1) {
  return window['go']['main']['App']['AddAsset'](arg1);
}

export function AssignRecordLocator(arg1) {
  return window['go']['main']['App']['AssignRecordLocator'](arg1);
}

export function ChangeImage(arg1) {
  return window['go']['main']['App']['ChangeImage'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadManual(arg1, arg2) {
  return window['go']['main']['App']['DownloadManual'](arg1, arg2);
}

export function DownloadReceipt(arg1) {
  return window['go']['main']['App']['DownloadReceipt'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetDefaultSearchMode() {
  return window['go']['main']['App']['GetDefaultSearchMode']();
}

export function GetProductVersion() {
  return window['go']['main']['App']['GetProductVersion']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RemoveImage(arg1) {
  return window['go']['main']['App']['RemoveImage'](arg1);
}

export function RemoveManual(arg1) {
  return window['go']['main']['App']['RemoveManual'](arg1);
}

export function RemoveReceipt(arg1) {
  return window['go']['main']['App']['RemoveReceipt'](arg1);
}

export function SearchModeBoolean(arg1) {
  return window['go']['main']['App']['SearchModeBoolean'](arg1);
}

export function SearchModeFullText(arg1) {
  return window['go']['main']['App']['SearchModeFullText'](arg1);
}

export function SearchModeFullTextWithQueryExpansion(arg1) {
  return window['go']['main']['App']['SearchModeFullTextWithQueryExpansion'](arg1);
}

export function SearchModeRegular(arg1, arg2) {
  return window['go']['main']['App']['SearchModeRegular'](arg1, arg2);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetDefaultSearchMode(arg1) {
  return window['go']['main']['App']['SetDefaultSearchMode'](arg1);
}

export function ToggleMissing(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMissing'](arg1, arg2, arg3);
}

export function UpdateAsset(arg1, arg2) {
  return window['go']['main']['App']['UpdateAsset'](arg1, arg2);
}

export function UpdateUserAccessLevel(arg1) {
  return window['go']['main']['App']['UpdateUserAccessLevel'](arg1);
}

export function UploadManual(arg1) {
  return window['go']['main']['App']['UploadManual'](arg1);
}

export function UploadReceipt(arg1) {
  return window['go']['main']['App']['UploadReceipt'](arg1);
}
