// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAsset(arg1:Record<string, string>):Promise<number>;

export function AddGroupAssetAssociatedById(arg1:number,arg2:number):Promise<void>;

export function AddGroupAssetAssociatedByRecordLocator(arg1:number,arg2:number):Promise<void>;

export function AddLabData(arg1:number,arg2:main.LabDataType,arg3:number,arg4:string,arg5:string,arg6:boolean,arg7:string):Promise<void>;

export function AddSetRecordAssociatedByGroup(arg1:number,arg2:number):Promise<void>;

export function AddSetRecordAssociatedById(arg1:number,arg2:number):Promise<void>;

export function AddSetRecordAssociatedByRecordLocator(arg1:number,arg2:number):Promise<void>;

export function AssignRecordLocator(arg1:number):Promise<void>;

export function ChangeImage(arg1:number):Promise<boolean>;

export function CreateGroup(arg1:string):Promise<number>;

export function CreateLab(arg1:string,arg2:string):Promise<void>;

export function CreateLabCourse(arg1:string,arg2:string):Promise<void>;

export function CreateSet(arg1:string):Promise<number>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteGroup(arg1:number):Promise<void>;

export function DeleteGroupAssetAssociatedById(arg1:number,arg2:number):Promise<void>;

export function DeleteGroupAssetAssociatedByRecordLocator(arg1:number,arg2:number):Promise<void>;

export function DeleteLab(arg1:number):Promise<void>;

export function DeleteLabCourse(arg1:string):Promise<void>;

export function DeleteSet(arg1:number):Promise<void>;

export function DeleteSetRecordAssociatedByGroup(arg1:number,arg2:number):Promise<void>;

export function DeleteSetRecordAssociatedById(arg1:number,arg2:number):Promise<void>;

export function DeleteSetRecordAssociatedByRecordLocator(arg1:number,arg2:number):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function DownloadManual(arg1:number,arg2:number):Promise<boolean>;

export function DownloadReceipt(arg1:number):Promise<boolean>;

export function DuplicateAsset(arg1:number):Promise<number>;

export function ExportAssetsCSV(arg1:Array<number>):Promise<void>;

export function ExportAssetsPDF(arg1:Array<number>):Promise<void>;

export function ExportGroupCSV(arg1:number):Promise<void>;

export function ExportGroupPDF(arg1:number):Promise<void>;

export function ExportLabCSV(arg1:number):Promise<void>;

export function ExportLabPDF(arg1:number):Promise<void>;

export function ExportSetCSV(arg1:number):Promise<void>;

export function ExportSetPDF(arg1:number):Promise<void>;

export function GetAsset(arg1:number):Promise<main.Asset>;

export function GetAssetGroups(arg1:number):Promise<Array<main.Group>>;

export function GetAssetSets(arg1:number):Promise<Array<main.Set>>;

export function GetDefaultSearchMode():Promise<string>;

export function GetGroupAssets(arg1:number):Promise<Array<main.CollectionRecord>>;

export function GetGroupName(arg1:number):Promise<string>;

export function GetGroups():Promise<Array<main.Group>>;

export function GetLabCourses():Promise<Array<main.LabCourse>>;

export function GetLabData(arg1:number):Promise<Array<main.LabData>>;

export function GetLabDetails(arg1:number):Promise<main.LabDetails>;

export function GetLabs(arg1:string):Promise<Array<main.Lab>>;

export function GetProductVersion():Promise<string>;

export function GetSetName(arg1:number):Promise<string>;

export function GetSetRecords(arg1:number):Promise<Array<main.CollectionRecord>>;

export function GetSets():Promise<Array<main.Set>>;

export function GetUsers():Promise<Array<main.User>>;

export function Login(arg1:string,arg2:string):Promise<number>;

export function RemoveImage(arg1:number):Promise<void>;

export function RemoveLabData(arg1:number):Promise<void>;

export function RemoveManual(arg1:number):Promise<void>;

export function RemoveReceipt(arg1:number):Promise<void>;

export function RenameGroup(arg1:number,arg2:string):Promise<void>;

export function RenameLab(arg1:number,arg2:string):Promise<void>;

export function RenameLabCourse(arg1:string,arg2:string):Promise<void>;

export function RenameSet(arg1:number,arg2:string):Promise<void>;

export function RunCustomSQL():Promise<void>;

export function SearchModeBoolean(arg1:string):Promise<Array<main.Asset>>;

export function SearchModeFullText(arg1:string):Promise<Array<main.Asset>>;

export function SearchModeFullTextWithQueryExpansion(arg1:string):Promise<Array<main.Asset>>;

export function SearchModeRegular(arg1:string,arg2:string):Promise<Array<main.Asset>>;

export function SelectFile(arg1:string):Promise<string>;

export function SetDefaultSearchMode(arg1:string):Promise<void>;

export function ToggleMissing(arg1:number,arg2:boolean,arg3:string):Promise<void>;

export function UpdateAsset(arg1:number,arg2:Record<string, string>):Promise<void>;

export function UpdateLabData(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateUserAccessLevel(arg1:main.User):Promise<void>;

export function UploadManual(arg1:number):Promise<boolean>;

export function UploadReceipt(arg1:number):Promise<boolean>;
